name: flutter_instagram_stories
homepage: https://github.com/awaik/flutter_instagram_stories
description: Display stories just like Whatsapp & Instagram. Built-in groups (multiple stories with one icon), cache, video, gifs. For now, it works with the Firestore database only.
version: 0.1.4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^1.4.1
  rxdart: ^0.24.1
  video_player: ^0.10.11+2
  cached_network_image: ^2.2.0+1
  json_annotation: ^3.0.1
  skeleton_text: ^1.0.0
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  dotted_border: ^1.0.6

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  test: ^1.15.3
